/**
 * Cron Job Status API
 * This endpoint checks the status of the auto-campaign generation cron job
 * Returns last execution time, recent campaigns, and cron configuration
 */

import { NextResponse } from "next/server"
import admin from "firebase-admin"

function initAdmin() {
  if (!admin.apps.length) {
    const projectId = process.env.FIREBASE_PROJECT_ID
    const clientEmail = process.env.FIREBASE_CLIENT_EMAIL
    let privateKey = process.env.FIREBASE_PRIVATE_KEY

    if (privateKey && privateKey.startsWith('"') && privateKey.endsWith('"')) {
      privateKey = privateKey.slice(1, -1)
    }
    if (privateKey) {
      privateKey = privateKey.replace(/\\n/g, "\n")
    }

    if (!projectId || !clientEmail || !privateKey) {
      return false
    }

    admin.initializeApp({
      credential: admin.credential.cert({ projectId, clientEmail, privateKey }),
    })
  }
  return true
}

/**
 * GET /api/auto-campaigns/status
 * Returns cron job status, last execution, and recent campaigns
 */
export async function GET() {
  try {
    const ok = initAdmin()
    if (!ok) {
      return NextResponse.json(
        { error: "Server not configured for admin" },
        { status: 500 }
      )
    }

    const db = admin.firestore()

    // Get cron execution logs (last 10)
    let cronLogs: any[] = []
    try {
      const cronLogsRef = db.collection("cron_logs")
        .orderBy("executedAt", "desc")
        .limit(10)
      const cronLogsSnapshot = await cronLogsRef.get()
      cronLogs = cronLogsSnapshot.docs.map(doc => {
        const data = doc.data()
        return {
          id: doc.id,
          executedAt: data.executedAt?.toDate?.()?.toISOString() || data.executedAt,
          success: data.success,
          campaignsGenerated: data.campaignsGenerated || 0,
          message: data.message,
          healthDaysChecked: data.healthDaysChecked || [],
          error: data.error,
          triggeredBy: data.triggeredBy || "unknown",
        }
      })
    } catch (error) {
      console.error("Error fetching cron logs:", error)
      // Continue without logs if query fails (e.g., missing index)
    }

    // Get last execution
    const lastExecution = cronLogs.length > 0 ? cronLogs[0] : null

    // Get recent auto-generated campaigns (last 7 days)
    let recentCampaigns: any[] = []
    try {
      const sevenDaysAgo = new Date()
      sevenDaysAgo.setDate(sevenDaysAgo.getDate() - 7)
      const recentCampaignsRef = db.collection("campaigns")
        .where("metadata.autoGenerated", "==", true)
        .where("createdAt", ">=", admin.firestore.Timestamp.fromDate(sevenDaysAgo))
        .orderBy("createdAt", "desc")
        .limit(10)
      const recentCampaignsSnapshot = await recentCampaignsRef.get()
      recentCampaigns = recentCampaignsSnapshot.docs.map(doc => {
        const data = doc.data()
        return {
          id: doc.id,
          title: data.title,
          healthDay: data.metadata?.healthAwarenessDay,
          healthDayDate: data.metadata?.healthDayDate,
          createdAt: data.createdAt?.toDate?.()?.toISOString() || data.createdAt,
          status: data.status,
        }
      })
    } catch (error) {
      console.error("Error fetching recent campaigns:", error)
      // Continue without recent campaigns if query fails (e.g., missing index)
    }

    // Calculate next cron execution (midnight IST = 18:30 UTC)
    const now = new Date()
    const istOffset = 5.5 * 60 * 60 * 1000 // IST offset in milliseconds
    
    // Get current time in IST
    const utcTime = now.getTime() + (now.getTimezoneOffset() * 60 * 1000)
    const istTime = new Date(utcTime + istOffset)
    
    // Calculate next midnight IST
    const nextCronIST = new Date(istTime)
    nextCronIST.setUTCHours(0, 0, 0, 0)
    nextCronIST.setUTCDate(nextCronIST.getUTCDate() + 1) // Next midnight IST
    
    // Convert IST midnight to UTC for cron schedule
    // IST midnight = 18:30 UTC previous day
    const nextCronUTC = new Date(nextCronIST.getTime() - istOffset)

    // Get today's date in IST
    const todayIST = new Date(istTime)
    todayIST.setUTCHours(0, 0, 0, 0)
    const todayDateString = `${String(todayIST.getUTCMonth() + 1).padStart(2, '0')}-${String(todayIST.getUTCDate()).padStart(2, '0')}`

    // Check if cron is configured (check vercel.json by checking if endpoint exists)
    const cronConfigured = true // Assume configured if endpoint exists

    // Get today's health awareness days (uses IST internally)
    const { getHealthAwarenessDaysForToday } = await import("@/server/healthAwarenessDays")
    const todayHealthDays = getHealthAwarenessDaysForToday()

    return NextResponse.json({
      success: true,
      cron: {
        configured: cronConfigured,
        schedule: "30 18 * * *", // Daily at 18:30 UTC (midnight IST)
        scheduleIST: "0 0 * * *", // Daily at midnight IST (display only)
        nextExecution: nextCronUTC.toISOString(),
        nextExecutionFormatted: new Date(nextCronUTC).toLocaleString("en-IN", {
          timeZone: "Asia/Kolkata",
          weekday: "long",
          year: "numeric",
          month: "long",
          day: "numeric",
          hour: "2-digit",
          minute: "2-digit",
          timeZoneName: "short",
        }),
      },
      lastExecution: lastExecution,
      executionHistory: cronLogs,
      recentCampaigns: recentCampaigns,
      today: {
        date: todayDateString,
        dateIST: `${String(todayIST.getUTCMonth() + 1).padStart(2, '0')}/${String(todayIST.getUTCDate()).padStart(2, '0')}/${todayIST.getUTCFullYear()}`,
        healthDaysCount: todayHealthDays.length,
        healthDays: todayHealthDays.map(d => ({
          name: d.name,
          date: d.date,
          priority: d.priority,
        })),
      },
      status: lastExecution
        ? lastExecution.success
          ? "healthy"
          : "error"
        : "unknown",
    })
  } catch (error: any) {
    console.error("Error checking cron status:", error)
    return NextResponse.json(
      {
        success: false,
        error: error?.message || "Failed to check cron status",
      },
      { status: 500 }
    )
  }
}

