/**
 * ENT anatomy part descriptions - ear, throat, dental, nose, lungs, kidney
 */

export const entPartDescriptions: Record<string, { name: string; description: string }> = {
  // Ear
  Outer_Ear: { name: 'Outer Ear (Pinna/Auricle)', description: 'The visible external portion of the ear that collects sound waves and directs them into the ear canal. Common conditions: otitis externa, cauliflower ear, perichondritis.' },
  outer_ear: { name: 'Outer Ear (Pinna/Auricle)', description: 'The visible external portion of the ear that collects sound waves and directs them into the ear canal. Common conditions: otitis externa, cauliflower ear, perichondritis.' },
  Ear_Canal: { name: 'Ear Canal (External Auditory Canal)', description: 'A tube-like structure measuring approximately 2.5 cm that extends from the outer ear to the eardrum. Common conditions: otitis externa, cerumen impaction, foreign body.' },
  ear_canal: { name: 'Ear Canal (External Auditory Canal)', description: 'A tube-like structure measuring approximately 2.5 cm that extends from the outer ear to the eardrum. Common conditions: otitis externa, cerumen impaction, foreign body.' },
  Eardrum: { name: 'Eardrum (Tympanic Membrane)', description: 'A thin, cone-shaped membrane that separates the external ear from the middle ear. Common conditions: perforation, otitis media, tympanosclerosis.' },
  eardrum: { name: 'Eardrum (Tympanic Membrane)', description: 'A thin, cone-shaped membrane that separates the external ear from the middle ear. Common conditions: perforation, otitis media, tympanosclerosis.' },
  Ossicles: { name: 'Ossicles (Middle Ear Bones)', description: 'Three tiny bones (malleus, incus, stapes) that form a chain. Common conditions: otosclerosis, ossicular chain dislocation.' },
  ossicles: { name: 'Ossicles (Middle Ear Bones)', description: 'Three tiny bones (malleus, incus, stapes) that form a chain. Common conditions: otosclerosis, ossicular chain dislocation.' },
  Cochlea: { name: 'Cochlea', description: 'A spiral-shaped organ that converts sound vibrations into electrical signals. Common conditions: sensorineural hearing loss, Ménière\'s disease.' },
  cochlea: { name: 'Cochlea', description: 'A spiral-shaped organ that converts sound vibrations into electrical signals. Common conditions: sensorineural hearing loss, Ménière\'s disease.' },
  Semicircular_Canals: { name: 'Semicircular Canals', description: 'Fluid-filled tubes for balance. Common conditions: BPPV, labyrinthitis.' },
  semicircular_canals: { name: 'Semicircular Canals', description: 'Fluid-filled tubes for balance. Common conditions: BPPV, labyrinthitis.' },
  Auditory_Nerve: { name: 'Auditory Nerve', description: 'Carries electrical signals from the cochlea to the brain.' },
  auditory_nerve: { name: 'Auditory Nerve', description: 'Carries electrical signals from the cochlea to the brain.' },
  Ear: { name: 'Ear', description: 'The complete hearing and balance organ.' },
  ear: { name: 'Ear', description: 'The complete hearing and balance organ.' },
  // Throat
  Pharynx: { name: 'Pharynx', description: 'The muscular tube connecting nasal cavity and mouth to larynx and esophagus. Common conditions: pharyngitis, tonsillitis.' },
  pharynx: { name: 'Pharynx', description: 'The muscular tube connecting nasal cavity and mouth to larynx and esophagus. Common conditions: pharyngitis, tonsillitis.' },
  Larynx: { name: 'Larynx (Voice Box)', description: 'Contains the vocal cords. Common conditions: laryngitis, vocal cord polyps.' },
  larynx: { name: 'Larynx (Voice Box)', description: 'Contains the vocal cords. Common conditions: laryngitis, vocal cord polyps.' },
  Epiglottis: { name: 'Epiglottis', description: 'Leaf-shaped flap that covers the larynx during swallowing. Common conditions: epiglottitis.' },
  epiglottis: { name: 'Epiglottis', description: 'Leaf-shaped flap that covers the larynx during swallowing. Common conditions: epiglottitis.' },
  Trachea: { name: 'Trachea (Windpipe)', description: 'Connects the larynx to the bronchi. Common conditions: tracheitis.' },
  trachea: { name: 'Trachea (Windpipe)', description: 'Connects the larynx to the bronchi. Common conditions: tracheitis.' },
  Vocal_Cords: { name: 'Vocal Cords', description: 'Two bands of muscle tissue that vibrate to produce sound.' },
  vocal_cords: { name: 'Vocal Cords', description: 'Two bands of muscle tissue that vibrate to produce sound.' },
  // Dental
  Teeth: { name: 'Teeth (Dentition)', description: 'Hard structures used for biting and chewing.' },
  teeth: { name: 'Teeth (Dentition)', description: 'Hard structures used for biting and chewing.' },
  Gums: { name: 'Gums (Gingiva)', description: 'Soft tissue surrounding and supporting the teeth.' },
  gums: { name: 'Gums (Gingiva)', description: 'Soft tissue surrounding and supporting the teeth.' },
  Tongue: { name: 'Tongue', description: 'Muscular organ for taste, speech, and swallowing.' },
  tongue: { name: 'Tongue', description: 'Muscular organ for taste, speech, and swallowing.' },
  Mandible: { name: 'Mandible (Lower Jaw)', description: 'The largest bone of the face, forming the lower jaw.' },
  mandible: { name: 'Mandible (Lower Jaw)', description: 'The largest bone of the face, forming the lower jaw.' },
  Palate: { name: 'Palate (Roof of Mouth)', description: 'The roof of the mouth separating oral and nasal cavities.' },
  palate: { name: 'Palate (Roof of Mouth)', description: 'The roof of the mouth separating oral and nasal cavities.' },
  Oral_Mucosa: { name: 'Oral Mucosa', description: 'Mucous membrane lining the mouth.' },
  oral_mucosa: { name: 'Oral Mucosa', description: 'Mucous membrane lining the mouth.' },
  Salivary_Glands: { name: 'Salivary Glands', description: 'Glands that produce saliva.' },
  salivary_glands: { name: 'Salivary Glands', description: 'Glands that produce saliva.' },
  Wisdom_Teeth: { name: 'Wisdom Teeth (Third Molars)', description: 'Last molars to erupt, often causing problems.' },
  wisdom_teeth: { name: 'Wisdom Teeth (Third Molars)', description: 'Last molars to erupt, often causing problems.' },
  // Nose
  Nostrils: { name: 'Nostrils (Nasal Vestibule)', description: 'External openings of the nose.' },
  nostrils: { name: 'Nostrils (Nasal Vestibule)', description: 'External openings of the nose.' },
  Nasal_Cavity: { name: 'Nasal Cavity', description: 'Air-filled space that filters and humidifies inhaled air.' },
  nasal_cavity: { name: 'Nasal Cavity', description: 'Air-filled space that filters and humidifies inhaled air.' },
  Nasal_Septum: { name: 'Nasal Septum', description: 'Wall dividing the nasal cavity into left and right.' },
  nasal_septum: { name: 'Nasal Septum', description: 'Wall dividing the nasal cavity into left and right.' },
  Turbinates: { name: 'Turbinates (Nasal Conchae)', description: 'Bony structures that warm and filter air.' },
  turbinates: { name: 'Turbinates (Nasal Conchae)', description: 'Bony structures that warm and filter air.' },
  Sinuses: { name: 'Sinuses (Paranasal Sinuses)', description: 'Air-filled spaces in the bones around the nose.' },
  sinuses: { name: 'Sinuses (Paranasal Sinuses)', description: 'Air-filled spaces in the bones around the nose.' },
  // Lungs
  Bronchi: { name: 'Bronchi', description: 'Main air passages branching from the trachea.' },
  bronchi: { name: 'Bronchi', description: 'Main air passages branching from the trachea.' },
  Lungs: { name: 'Lungs', description: 'Paired organs responsible for gas exchange.' },
  lungs: { name: 'Lungs', description: 'Paired organs responsible for gas exchange.' },
  Heart: { name: 'Heart', description: 'The muscular organ that pumps blood.' },
  heart: { name: 'Heart', description: 'The muscular organ that pumps blood.' },
  // Kidney
  Kidney: { name: 'Kidney', description: 'Paired organs that filter blood and remove waste.' },
  kidney: { name: 'Kidney', description: 'Paired organs that filter blood and remove waste.' },
  Renal_Pelvis: { name: 'Renal Pelvis', description: 'Funnel-shaped structure that collects urine.' },
  Ureter: { name: 'Ureter', description: 'Tubes that carry urine from kidneys to bladder.' },
  Cortex: { name: 'Renal Cortex', description: 'Outer region containing glomeruli.' },
  Medulla: { name: 'Renal Medulla', description: 'Inner region containing loops of Henle.' },
  // Skeleton
  Skull: { name: 'Skull', description: 'Bony structure that protects the brain and supports the face. Common conditions: fracture, concussion.' },
  skull: { name: 'Skull', description: 'Bony structure that protects the brain and supports the face. Common conditions: fracture, concussion.' },
  Spine: { name: 'Spine (Vertebral Column)', description: 'Column of vertebrae protecting the spinal cord. Common conditions: disc herniation, stenosis, scoliosis.' },
  spine: { name: 'Spine (Vertebral Column)', description: 'Column of vertebrae protecting the spinal cord. Common conditions: disc herniation, stenosis, scoliosis.' },
  Ribcage: { name: 'Ribcage', description: 'Bony cage formed by ribs and sternum protecting the thoracic organs. Common conditions: rib fracture, costochondritis.' },
  ribcage: { name: 'Ribcage', description: 'Bony cage formed by ribs and sternum protecting the thoracic organs. Common conditions: rib fracture, costochondritis.' },
  Sternum: { name: 'Sternum (Breastbone)', description: 'Flat bone in the center of the chest connecting the ribs. Common conditions: fracture, costochondritis.' },
  sternum: { name: 'Sternum (Breastbone)', description: 'Flat bone in the center of the chest connecting the ribs. Common conditions: fracture, costochondritis.' },
  Pelvis: { name: 'Pelvis', description: 'Bony structure connecting the spine to the lower limbs. Common conditions: fracture, osteoarthritis.' },
  pelvis: { name: 'Pelvis', description: 'Bony structure connecting the spine to the lower limbs. Common conditions: fracture, osteoarthritis.' },
  Humerus: { name: 'Humerus', description: 'Upper arm bone connecting shoulder to elbow. Common conditions: fracture, rotator cuff involvement.' },
  humerus: { name: 'Humerus', description: 'Upper arm bone connecting shoulder to elbow. Common conditions: fracture, rotator cuff involvement.' },
  Radius: { name: 'Radius', description: 'One of two forearm bones (thumb side). Common conditions: fracture (e.g. Colles).' },
  radius: { name: 'Radius', description: 'One of two forearm bones (thumb side). Common conditions: fracture (e.g. Colles).' },
  Ulna: { name: 'Ulna', description: 'One of two forearm bones (pinky side). Common conditions: fracture.' },
  ulna: { name: 'Ulna', description: 'One of two forearm bones (pinky side). Common conditions: fracture.' },
  Femur: { name: 'Femur', description: 'Thigh bone, the longest bone in the body. Common conditions: fracture, osteoporosis.' },
  femur: { name: 'Femur', description: 'Thigh bone, the longest bone in the body. Common conditions: fracture, osteoporosis.' },
  Tibia: { name: 'Tibia', description: 'Shin bone, the larger of the two lower leg bones. Common conditions: fracture, stress fracture.' },
  tibia: { name: 'Tibia', description: 'Shin bone, the larger of the two lower leg bones. Common conditions: fracture, stress fracture.' },
  Fibula: { name: 'Fibula', description: 'Thinner lower leg bone running alongside the tibia. Common conditions: fracture.' },
  fibula: { name: 'Fibula', description: 'Thinner lower leg bone running alongside the tibia. Common conditions: fracture.' },
  Clavicle: { name: 'Clavicle (Collarbone)', description: 'Bone connecting sternum to shoulder. Common conditions: fracture.' },
  clavicle: { name: 'Clavicle (Collarbone)', description: 'Bone connecting sternum to shoulder. Common conditions: fracture.' },
  Scapula: { name: 'Scapula (Shoulder Blade)', description: 'Flat triangular bone at the back of the shoulder. Common conditions: fracture, winging.' },
  scapula: { name: 'Scapula (Shoulder Blade)', description: 'Flat triangular bone at the back of the shoulder. Common conditions: fracture, winging.' },
  Patella: { name: 'Patella (Kneecap)', description: 'Small bone protecting the knee joint. Common conditions: fracture, dislocation, chondromalacia.' },
  patella: { name: 'Patella (Kneecap)', description: 'Small bone protecting the knee joint. Common conditions: fracture, dislocation, chondromalacia.' },
  Radius_Ulna: { name: 'Radius & Ulna', description: 'Forearm bones (radius on thumb side, ulna on pinky side). Common conditions: fracture, dislocation.' },
  radius_ulna: { name: 'Radius & Ulna', description: 'Forearm bones (radius on thumb side, ulna on pinky side). Common conditions: fracture, dislocation.' },
  Tarsals: { name: 'Tarsals', description: 'Bones of the ankle and rear foot. Common conditions: fracture, sprain, arthritis.' },
  tarsals: { name: 'Tarsals', description: 'Bones of the ankle and rear foot. Common conditions: fracture, sprain, arthritis.' },
  Tibia_Fibula: { name: 'Tibia & Fibula', description: 'Lower leg bones (tibia is the shin bone, fibula is the thinner lateral bone). Common conditions: fracture, stress fracture.' },
  tibia_fibula: { name: 'Tibia & Fibula', description: 'Lower leg bones (tibia is the shin bone, fibula is the thinner lateral bone). Common conditions: fracture, stress fracture.' },
  Hand: { name: 'Hand', description: 'Bones and joints of the hand (carpals, metacarpals, phalanges). Common conditions: fracture, arthritis, carpal tunnel.' },
  hand: { name: 'Hand', description: 'Bones and joints of the hand (carpals, metacarpals, phalanges). Common conditions: fracture, arthritis, carpal tunnel.' },
}

export function getPartDescription(partName: string): { name: string; description: string } {
  if (entPartDescriptions[partName]) return entPartDescriptions[partName]
  const lowerName = partName.toLowerCase()
  for (const key in entPartDescriptions) {
    if (key.toLowerCase() === lowerName) return entPartDescriptions[key]
  }
  return { name: partName, description: `Selected part: ${partName}. Click to view detailed information.` }
}
